/** API prefixes that must reach FastAPI instead of Vite's SPA fallback. */
export const API_PROXY_PATHS = [
  "/auth",
  "/sessions",
  "/swarm/presets",
  "/swarm/runs",
  "/qveris",
  "/settings/llm",
  "/settings/data-sources",
  "/channels",
  "/mandate",
  "/live",
  "/upload",
  "/shadow-reports",
  "/scheduled-runs",
  "/dashboard",
  "/tdx",
  "/research-runs",
  "/macro",
  "/sectors",
  "/securities",
  "/committees",
  "/trade-plans",
  "/portfolios",
  "/strategy-runs",
  "/strategy",
  "/decision-chains",
  "/signals",
  "/paper",
] as const;
