import { useEffect, useState } from "react";
import { AlertTriangle, Loader2 } from "lucide-react";
import { api, type MoatResearch, type MoatResearchDimension } from "@/lib/api";

const statusLabel: Record<string, string> = { SUPPORTED: "事实支持较充分", PARTIAL: "初步判断", UNKNOWN: "暂无法判断", APPLICABLE: "适用", NOT_APPLICABLE: "当前行业不适用", UNKNOWN_APPLICABILITY: "适用性待确认", SUPPORTING: "支持性证据", MIXED: "证据有分歧", CHALLENGED: "存在反证", NO_SIGNAL: "暂无信号", REPEATED: "跨期重复", SINGLE_PERIOD: "单期资料", DETERIORATING: "出现恶化迹象" };
const tone: Record<string, string> = { SUPPORTED: "border-emerald-500/35 bg-emerald-500/10 text-emerald-800", PARTIAL: "border-amber-500/35 bg-amber-500/10 text-amber-800", UNKNOWN: "border-muted bg-muted/50 text-muted-foreground" };

function EvidenceLine({ item }: { item: MoatResearchDimension }) {
  const counts = item.evidence_counts;
  return <p className="mt-2 text-xs leading-5 text-muted-foreground">正式事实 {counts.quantified_fact + counts.disclosed_fact} 条 · 管理层声明 {counts.management_claim} 条 · 推断 {counts.inference} 条 · 反证 {counts.counter} 条<br />证据编号：{item.supporting_evidence_ids.concat(item.management_claim_ids, item.counter_evidence_ids).slice(0, 4).join("、") || "—"}</p>;
}

export function MoatResearchPanel({ stockCode, asOf }: { stockCode: string; asOf?: string }) {
  const [data, setData] = useState<MoatResearch | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { setLoading(true); setError(""); api.getMoatResearch(stockCode, asOf).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))).finally(() => setLoading(false)); }, [asOf, stockCode]);
  if (loading) return <section className="rounded-xl border bg-card p-5 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />综合已保存的竞争优势证据…</section>;
  if (error || !data) return <section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">竞争优势</h2><p className="mt-2 text-sm text-muted-foreground">{error || "当前资料暂不可用。"}</p></section>;
  const applicable = data.dimensions.filter((item) => item.applicability === "APPLICABLE");
  const preliminary = applicable.filter((item) => item.status === "PARTIAL");
  return <section className="rounded-xl border border-primary/25 bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-medium text-primary">COMPETITIVE ADVANTAGE · 证据综合</div><h2 className="mt-1 text-lg font-semibold">竞争优势</h2><p className="mt-1 text-sm text-muted-foreground">只综合已保存的正式披露、管理层表述与反证；不是“护城河评分”，不产生买卖结论。</p></div><span className="rounded bg-muted px-2 py-1 text-xs text-muted-foreground">截至 {data.research_as_of || "—"}</span></div>
    <p className="mt-4 rounded-lg bg-muted/40 p-3 text-sm leading-6">{data.moat_summary}</p>
    <div className="mt-4 grid gap-3 md:grid-cols-3"><article className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">行业上下文</div><strong className="mt-1 block">{data.industry_context.level3_name || "未确认"}</strong><p className="mt-1 text-xs text-muted-foreground">适用性：{statusLabel[data.industry_context.applicability_status] || data.industry_context.applicability_status}</p></article><article className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">资料状态</div><strong className="mt-1 block">{data.status === "READY" ? "已形成初步研究" : data.status === "PARTIAL" ? "资料部分可用" : "资料不足"}</strong><p className="mt-1 text-xs text-muted-foreground">证据库：{data.source_status.moat_evidence || "—"}</p></article><article className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">重要边界</div><strong className="mt-1 block">领先不等于护城河</strong><p className="mt-1 text-xs text-muted-foreground">龙头质量仅作同行事实背景。</p></article></div>
    {data.supported_advantages.length ? <div className="mt-5"><h3 className="font-semibold">当前有证据的竞争优势</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{data.supported_advantages.map((item) => <article key={item.dimension} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{item.label}</strong><span className={`rounded border px-2 py-1 text-xs ${tone[item.status]}`}>{statusLabel[item.status]}</span></div><p className="mt-2 text-sm leading-6">{item.summary}</p><p className="mt-2 text-xs text-muted-foreground">持续性：{statusLabel[item.persistence]} · {item.why_it_may_matter}</p><EvidenceLine item={item} /></article>)}</div></div> : <div className="mt-5 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">当前没有任何维度达到“较充分事实支持”的严格门槛；这不等于公司没有竞争优势，只表示现有资料还不能确认。</div>}
    {preliminary.length ? <div className="mt-5"><h3 className="font-semibold">仍需验证的初步判断</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{preliminary.filter((item) => !data.supported_advantages.some((advantage) => advantage.dimension === item.dimension)).map((item) => <article key={item.dimension} className="rounded-lg border border-amber-500/25 p-4"><strong>{item.label}</strong><p className="mt-2 text-sm leading-6">{item.summary}</p><EvidenceLine item={item} /></article>)}</div></div> : null}
    {data.moat_challenges.length ? <div className="mt-5 rounded-lg border border-amber-500/30 bg-amber-500/5 p-4"><h3 className="flex items-center gap-2 font-semibold text-amber-900"><AlertTriangle className="h-4 w-4" />不能忽略的反证</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-amber-900">{data.moat_challenges.map((item) => <li key={item.dimension}><strong>{item.label}</strong>：{item.summary}</li>)}</ul><p className="mt-2 text-xs text-amber-800">这些是研究反证，不会自动创建风险事件。</p></div> : null}
    <div className="mt-5 rounded-lg border border-dashed p-4"><h3 className="font-semibold">当前缺什么资料，为什么不能直接称为“护城河”</h3><p className="mt-1 text-xs text-muted-foreground">没有市场份额、客户验证、复购、成本拆解或技术性能等独立资料时，管理层声明和财务领先最多只是初步线索。</p><div className="mt-3 flex flex-wrap gap-2">{data.moat_data_gaps.slice(0, 12).map((gap) => <span key={gap} className="rounded bg-muted px-2 py-1 text-xs text-muted-foreground">{gap}</span>)}</div><p className="mt-3 text-xs text-muted-foreground">公式版本：{data.formula_version} · 页面请求不会下载 CNINFO、重算 L3、生成 Thesis 或刷新风险研究。</p></div>
  </section>;
}
