import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { AlertTriangle, Loader2, Play, Search } from "lucide-react";
import { toast } from "sonner";
import { api, type TdxFormulaScan, type TdxRecord } from "@/lib/api";
import { cn } from "@/lib/utils";
import { EmptyState, LoadingState, PageHeader, WorkspacePage, formatNumber } from "@/components/workspace/WorkspaceUI";

const TYPES = [[0, "技术指标"], [1, "条件选股"], [2, "专家系统"], [3, "K线形态"]] as const;
function pct(value: unknown) { const number = Number(value); return Number.isFinite(number) ? `${number > 0 ? "+" : ""}${number.toFixed(2)}%` : "—"; }
export function FormulaScanner() {
  const [type, setType] = useState(1);
  const [formulas, setFormulas] = useState<TdxRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<TdxRecord | null>(null);
  const [args, setArgs] = useState("");
  const [universe, setUniverse] = useState("all");
  const [period, setPeriod] = useState("1d");
  const [scan, setScan] = useState<TdxFormulaScan | null>(null);
  useEffect(() => { setLoading(true); api.getTdxData("formulas", { limit: 1000 }).then((result) => setFormulas(result.items)).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => formulas.filter((item) => Number(item.payload.formula_type) === type && (!query || item.name.toLowerCase().includes(query.toLowerCase()) || String(item.payload.acCode).toLowerCase().includes(query.toLowerCase()))), [formulas, query, type]);
  useEffect(() => { setSelected(visible[0] || null); }, [type]); // eslint-disable-line react-hooks/exhaustive-deps
  const poll = useCallback(async (id: string) => {
    const current = await api.getTdxFormulaScan(id); setScan(current);
    if (["queued", "running"].includes(current.status)) window.setTimeout(() => void poll(id), 1200);
  }, []);
  const start = async () => { if (!selected) return; try { const created = await api.startTdxFormulaScan({ formula_type: type, formula_code: String(selected.payload.acCode), formula_args: args, universe, period }); setScan(created); void poll(created.id); toast.success("公式扫描已在后台启动"); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "公式扫描启动失败"); } };
  if (loading) return <WorkspacePage><LoadingState label="正在读取通达信公式库…" /></WorkspacePage>;
  return <WorkspacePage><PageHeader eyebrow="TONGDAXIN / FORMULA" title="公式选股" description="扫描在独立后台任务中运行，不阻塞API。结果只写入本地缓存，不调用自选股、交易或任何客户端写入接口。" />
    <section className="grid min-h-[620px] gap-5 xl:grid-cols-[280px_360px_1fr]">
      <article className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="border-b p-4"><div className="grid grid-cols-2 gap-2">{TYPES.map(([key, label]) => <button key={key} onClick={() => setType(key)} className={cn("rounded-lg px-2 py-2 text-xs", type === key ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}>{label}</button>)}</div><label className="relative mt-3 block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索公式" className="w-full rounded-lg border bg-background py-2 pl-9 pr-3 text-sm" /></label></div><div className="max-h-[520px] overflow-y-auto divide-y">{visible.map((item) => <button key={item.key} onClick={() => setSelected(item)} className={cn("block w-full p-3 text-left text-sm hover:bg-muted/40", selected?.key === item.key && "bg-primary/10 text-primary")}><div className="font-medium">{item.name}</div><div className="mt-1 font-mono text-[10px] opacity-70">{String(item.payload.acCode)}</div></button>)}</div></article>
      <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="text-xs font-semibold text-primary">SCAN CONFIG</div><h2 className="mt-1 text-lg font-semibold">扫描配置</h2>{selected ? <div className="mt-5 space-y-4"><div className="rounded-lg bg-muted/50 p-4"><div className="font-medium">{selected.name}</div><div className="mt-1 font-mono text-xs text-muted-foreground">{String(selected.payload.acCode)} · {TYPES.find(([key]) => key === type)?.[1]}</div></div><label className="block text-xs text-muted-foreground">公式参数<input value={args} onChange={(event) => setArgs(event.target.value)} placeholder="例如 12,26,9；无参数可留空" className="mt-1 w-full rounded-lg border bg-background px-3 py-2 text-sm text-foreground" /></label><label className="block text-xs text-muted-foreground">股票范围<input value={universe} onChange={(event) => setUniverse(event.target.value.trim() || "all")} placeholder="all 或板块代码" className="mt-1 w-full rounded-lg border bg-background px-3 py-2 text-sm text-foreground" /></label><label className="block text-xs text-muted-foreground">K线周期<select value={period} onChange={(event) => setPeriod(event.target.value)} className="mt-1 w-full rounded-lg border bg-background px-3 py-2 text-sm text-foreground">{[["1d", "日线"], ["1w", "周线"], ["1m", "月线"], ["5m", "5分钟"], ["15m", "15分钟"], ["30m", "30分钟"], ["60m", "60分钟"]].map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><div className="flex gap-2 rounded-lg border border-warning/30 bg-warning/5 p-3 text-xs text-warning"><AlertTriangle className="h-4 w-4 shrink-0" />全市场扫描可能持续较长时间；板块范围可显著缩短耗时。</div><button onClick={() => void start()} disabled={Boolean(scan && ["queued", "running"].includes(scan.status))} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50"><Play className="h-4 w-4" />开始后台扫描</button></div> : <p className="mt-5 text-sm text-muted-foreground">请先从左侧选择公式。</p>}</article>
      <article className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="border-b p-5"><div className="text-xs font-semibold text-primary">SCAN RESULT</div><div className="mt-1 flex items-center justify-between"><h2 className="text-lg font-semibold">扫描结果</h2>{scan ? <span className="text-xs text-muted-foreground">{scan.progress}/{scan.total}</span> : null}</div>{scan && ["queued", "running"].includes(scan.status) ? <div className="mt-4"><div className="flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin" />{scan.message}</div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${scan.total ? scan.progress / scan.total * 100 : 2}%` }} /></div></div> : null}{scan?.error ? <div className="mt-3 text-sm text-danger">{scan.error}</div> : null}</div>{!scan ? <EmptyState title="尚未运行扫描" body="配置公式、范围和周期后启动后台任务。" /> : scan.results.length ? <div className="divide-y">{scan.results.map((row) => <Link key={row.code} to={`/company/CN/${row.code}`} className="grid grid-cols-[1fr_90px_80px] items-center gap-3 p-4 text-sm hover:bg-muted/40"><div><div className="font-medium">{row.name || row.code}</div><div className="font-mono text-[11px] text-muted-foreground">{row.code} · {row.signals?.map((signal) => `${signal.line}:${String(signal.value)}`).join(" · ")}</div></div><span className="text-right font-mono">{formatNumber(row.price)}</span><span className={cn("text-right font-mono", Number(row.change_pct) > 0 ? "text-market-up" : Number(row.change_pct) < 0 ? "text-market-down" : "text-muted-foreground")}>{pct(row.change_pct)}</span></Link>)}</div> : scan.status === "completed" ? <EmptyState title="扫描完成，未命中股票" body="可调整参数、周期或股票范围后重试。" /> : null}</article>
    </section>
  </WorkspacePage>;
}
