import { useCallback, useEffect, useState } from "react";
import { Search } from "lucide-react";
import { api, type TdxFundResult } from "@/lib/api";
import { cn } from "@/lib/utils";
import { EmptyState, LoadingState, PageHeader, WorkspacePage, formatNumber } from "@/components/workspace/WorkspaceUI";

type Dict = Record<string, unknown>;
const TABS = ["ETF", "REITs", "可转债", "场内基金", "新股/新债"];
function pick(row: Dict, ...keys: string[]): unknown { for (const key of keys) if (row[key] !== undefined && row[key] !== null && row[key] !== "") return row[key]; return "—"; }
function pct(value: unknown) { const number = Number(value); return Number.isFinite(number) ? `${number > 0 ? "+" : ""}${number.toFixed(2)}%` : "—"; }

export function Funds() {
  const [category, setCategory] = useState("ETF");
  const [query, setQuery] = useState("");
  const [data, setData] = useState<TdxFundResult | null>(null);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setData(await api.getTdxFunds({ category, query, limit: 500 })); } finally { setLoading(false); } }, [category, query]);
  useEffect(() => { void load(); }, [load]);
  return <WorkspacePage><PageHeader eyebrow="A-SHARE / FUNDS & BONDS" title="基金与债券" description="ETF、REITs、可转债、场内基金以及新股新债申购信息集中在一个页面。" />
    <section className="flex flex-col gap-4 rounded-xl border bg-card p-4 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{TABS.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn("rounded-full px-4 py-1.5 text-sm", category === item ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}>{item}</button>)}</div><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input onKeyDown={(event) => event.key === "Enter" && setQuery(event.currentTarget.value.trim())} placeholder="搜索代码或名称" className="w-56 rounded-lg border bg-background py-2 pl-9 pr-3 text-sm" /></label></section>
    {loading ? <LoadingState /> : !data?.items.length ? <EmptyState title={`暂无${category}数据`} body="请在数据中心单独更新“基金债券”模块。" /> : category === "可转债" ? <BondTable data={data} /> : category === "新股/新债" ? <IpoTable data={data} /> : <FundTable data={data} />}
  </WorkspacePage>;
}

function FundTable({ data }: { data: TdxFundResult }) { return <TableShell title={`${data.category}（${data.total}）`} asOf={data.as_of}><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-4">代码 / 名称</th><th className="p-4 text-right">现价</th><th className="p-4 text-right">涨跌幅</th><th className="p-4 text-right">成交量（手）</th><th className="p-4 text-right">IOPV</th><th className="p-4 text-right">折溢价</th><th className="p-4 text-right">总份额(万份) / 市值(亿元)</th><th className="p-4">跟踪指数</th></tr></thead><tbody className="divide-y">{data.items.map((row, index) => { const item = row as Dict; const price = Number(pick(item, "price", "NowPrice", "Now")); const iopv = Number(pick(item, "IOPV", "iopv")); const premium = Number.isFinite(price) && Number.isFinite(iopv) && iopv > 0 ? (price / iopv - 1) * 100 : undefined; return <tr key={`${String(pick(item, "code", "Code"))}:${index}`} className="hover:bg-muted/30"><td className="p-4"><div className="font-medium">{String(pick(item, "name", "Name"))}</div><div className="font-mono text-[11px] text-muted-foreground">{String(pick(item, "code", "Code"))}</div></td><td className="p-4 text-right font-mono">{formatNumber(price)}</td><td className={cn("p-4 text-right font-mono", Number(pick(item, "change_pct")) > 0 && "text-market-up", Number(pick(item, "change_pct")) < 0 && "text-market-down")}>{pct(pick(item, "change_pct"))}</td><td className="p-4 text-right font-mono">{formatNumber(pick(item, "volume_lots", "Volume"), 0)}</td><td className="p-4 text-right font-mono">{formatNumber(iopv)}</td><td className="p-4 text-right font-mono">{pct(premium)}</td><td className="p-4 text-right font-mono">{String(pick(item, "Zgb", "TotalScale", "Scale"))} / {String(pick(item, "Sz", "MarketValue"))}</td><td className="p-4 text-xs text-muted-foreground">{String(pick(item, "index_code", "IndexName", "TrackIndex", "ZSName"))}</td></tr>; })}</tbody></table></TableShell>; }
function BondTable({ data }: { data: TdxFundResult }) { return <TableShell title={`可转债（${data.total}）`} asOf={data.as_of}><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-4">转债</th><th className="p-4">正股</th><th className="p-4 text-right">转债现价</th><th className="p-4 text-right">转股价</th><th className="p-4 text-right">转股价值</th><th className="p-4 text-right">溢价率</th><th className="p-4 text-right">剩余规模</th><th className="p-4 text-right">评级</th><th className="p-4 text-right">到期日</th></tr></thead><tbody className="divide-y">{data.items.map((row, index) => { const item = row as Dict; return <tr key={`${String(pick(item, "KZZCode"))}:${index}`}><td className="p-4"><div className="font-medium">{String(pick(item, "KZZName"))}</div><div className="font-mono text-xs text-muted-foreground">{String(pick(item, "KZZCode"))}</div></td><td className="p-4"><div>{String(pick(item, "HSName"))}</div><div className="font-mono text-xs text-muted-foreground">{String(pick(item, "HSCode"))}</div></td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "KZZNow")))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "ZGPrice")))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "ZGValue")))}</td><td className="p-4 text-right font-mono">{pct(Number(pick(item, "KZZYj")))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "RestScope")))}</td><td className="p-4 text-right">{String(pick(item, "KZZScore"))}</td><td className="p-4 text-right font-mono">{date(pick(item, "EndDate"))}</td></tr>; })}</tbody></table></TableShell>; }
function IpoTable({ data }: { data: TdxFundResult }) { return <TableShell title={`新股 / 新债（${data.total}）`} asOf={data.as_of}><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-4">代码 / 名称</th><th className="p-4 text-right">申购日期</th><th className="p-4 text-right">申购价格</th><th className="p-4 text-right">最大申购</th><th className="p-4 text-right">发行PE</th></tr></thead><tbody className="divide-y">{data.items.map((row, index) => { const item = row as Dict; return <tr key={`${String(pick(item, "Code"))}:${index}`}><td className="p-4"><div className="font-medium">{String(pick(item, "Name"))}</div><div className="font-mono text-xs text-muted-foreground">{String(pick(item, "Code", "SGCode"))}</div></td><td className="p-4 text-right font-mono">{date(pick(item, "SGDate"))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "SGPrice")))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "MaxSG")))}</td><td className="p-4 text-right font-mono">{formatNumber(Number(pick(item, "PE_Issue")))}</td></tr>; })}</tbody></table></TableShell>; }
function TableShell({ title, asOf, children }: { title: string; asOf?: string | null; children: React.ReactNode }) { return <section className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">{title}</h2><span className="text-xs text-muted-foreground">{asOf ? new Date(asOf).toLocaleString("zh-CN", { hour12: false }) : "—"}</span></div><div className="overflow-x-auto">{children}</div></section>; }
function date(value: unknown) { const text = String(value ?? ""); return /^\d{8}$/.test(text) ? `${text.slice(0, 4)}-${text.slice(4, 6)}-${text.slice(6)}` : text || "—"; }
