import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { FileText, Search } from "lucide-react";
import { api, type ResearchReport } from "@/lib/api";
import { EmptyState, LoadingState, PageHeader, SourceBadge, WorkspacePage } from "@/components/workspace/WorkspaceUI";

const typeLabels: Record<string, string> = { market: "市场", macro: "宏观", sector: "行业", company: "公司", committee: "投委会", portfolio: "组合", backtest: "回测" };
export function ResearchReports() {
  const [items, setItems] = useState<ResearchReport[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [type, setType] = useState("all");
  useEffect(() => { api.listResearchReports().then(setItems).finally(() => setLoading(false)); }, []);
  const types = useMemo(() => Array.from(new Set(items.map((item) => item.report_type))), [items]);
  const shown = useMemo(() => items.filter((item) => (type === "all" || item.report_type === type) && (!query.trim() || `${item.title} ${item.summary} ${item.symbol ?? ""}`.toLowerCase().includes(query.toLowerCase()))), [items, query, type]);
  return <WorkspacePage><PageHeader eyebrow="REPORT LIBRARY" title="研究报告" description="报告是正式交付物，和 Agent 会话、Swarm 过程及回测 Run 分开保存并相互关联。" /><section className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索标题、摘要或证券代码" className="w-full rounded-lg border bg-card py-2.5 pl-10 pr-4 text-sm outline-none focus:border-primary" /></label><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-lg border bg-card px-3 py-2 text-sm"><option value="all">全部类型</option>{types.map((value) => <option key={value} value={value}>{typeLabels[value] ?? value}</option>)}</select></section>{loading ? <LoadingState /> : !shown.length ? <EmptyState title="暂无匹配报告" /> : <section className="grid gap-4 lg:grid-cols-2">{shown.map((report) => <Link key={report.id} to={`/reports/${report.id}`} className="group rounded-xl border bg-card p-5 shadow-sm transition hover:border-primary/40"><div className="flex items-start justify-between gap-4"><div className="rounded-lg bg-primary/10 p-2 text-primary"><FileText className="h-5 w-5" /></div><SourceBadge status={report.source_status} asOf={report.data_as_of} /></div><h2 className="mt-4 text-lg font-semibold group-hover:text-primary">{report.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-foreground">{report.summary}</p><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>{typeLabels[report.report_type] ?? report.report_type}</span><span>{report.market ? `${report.market} · ${report.symbol ?? ""}` : "全市场"}</span></div></Link>)}</section>}</WorkspacePage>;
}
